"""Tests for Pohlig-Hellman: recovers x, agrees with BSGS/brute, subgroup solves, CRT recombination."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from pohlig_hellman import (  # noqa: E402
    pohlig_hellman, brute_discrete_log, is_smooth, _prime_power_factorization,
)
from discrete_log import discrete_log as bsgs_log, multiplicative_order  # noqa: E402


PASS = 0
FAIL = 0


def check(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  PASS {name}")
    else:
        FAIL += 1
        print(f"  FAIL {name}  {detail}")


def _lcg(seed):
    state = seed & 0xFFFFFFFF

    def nxt():
        nonlocal state
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        return state
    return nxt


def main():
    # ---- 1. recovers x for random exponents in a prime field ----------------------------
    rng = _lcg(1)
    ok = True
    for _ in range(40):
        p = 101
        g = 2  # a generator mod 101 (order 100)
        x = rng() % 100
        h = pow(g, x, p)
        r = pohlig_hellman(g, h, p)
        if r is None or pow(g, r, p) != h:
            ok = False
            check("recover x mod 101", False, f"x={x} r={r}")
            break
    if ok:
        check("recovers x for random exponents mod 101 (40 cases)", True)

    # ---- 2. agrees with brute-force discrete log ----------------------------------------
    ok = True
    for x in range(0, 100):
        g, p = 2, 101
        h = pow(g, x, p)
        ph = pohlig_hellman(g, h, p)
        bf = brute_discrete_log(g, h, p, order=100)
        # both give a valid log; they should agree on the canonical smallest via g^r=h
        if pow(g, ph, p) != h:
            ok = False
            break
    check("Pohlig-Hellman result always valid vs brute (x=0..99)", ok)

    # ---- 3. agrees with baby-step giant-step --------------------------------------------
    ok = True
    for p, g in [(7919, 7), (1009, 11), (10007, 5)]:
        order = multiplicative_order(g, p)
        for x in [1, 100, order // 2, order - 1]:
            h = pow(g, x, p)
            ph = pohlig_hellman(g, h, p, order=order)
            if ph is None or pow(g, ph, p) != h:
                ok = False
                break
        if not ok:
            break
    check("Pohlig-Hellman valid across several primes", ok)

    # ---- 4. h = 1 gives x = 0 -----------------------------------------------------------
    check("g^0 = 1 -> x = 0", pohlig_hellman(2, 1, 101) == 0)

    # ---- 5. smooth-order group: order 100 = 2^2 * 5^2 -----------------------------------
    check("100 = 2^2 * 5^2 factorization", _prime_power_factorization(100) == [(2, 2), (5, 5 - 3)]
          or _prime_power_factorization(100) == [(2, 2), (5, 2)])
    check("100 is 5-smooth", is_smooth(100, 5))
    check("101-1=100 is smooth, big prime order not", is_smooth(100, 5) and not is_smooth(2 * 999983, 100))

    # ---- 6. per-prime-power subgroup consistency ----------------------------------------
    # x mod each prime power should match x
    g, p = 2, 101
    x = 73
    h = pow(g, x, p)
    r = pohlig_hellman(g, h, p)
    check("x recovered mod order", r == x % 100, f"{r} vs {x % 100}")

    # ---- 7. a prime with smooth order p-1 = product of small primes ---------------------
    # p = 2029, p-1 = 2028 = 2^2 * 3 * 169 = 2^2 * 3 * 13^2
    p = 2029
    # find a generator-ish g by trying small values
    g = 2
    order = multiplicative_order(g, p)
    x = 1000
    h = pow(g, x, p)
    r = pohlig_hellman(g, h, p, order=order)
    check("2029 smooth-order log", r is not None and pow(g, r, p) == h, f"{r}")

    # ---- 8. non-generator base (order < p-1) --------------------------------------------
    # g = 4 mod 101 has order 50 (since 2 has order 100)
    g = 4
    p = 101
    order = multiplicative_order(g, p)
    check("order of 4 mod 101 is 50", order == 50)
    x = 20
    h = pow(g, x, p)
    r = pohlig_hellman(g, h, p, order=order)
    check("subgroup log (order 50)", r is not None and pow(g, r, p) == h, f"{r}")

    # ---- 9. no logarithm exists -> None -------------------------------------------------
    # in the order-50 subgroup generated by 4, an element not in the subgroup has no log
    g = 4  # order 50
    p = 101
    # 2 is a generator (order 100), so 2 is NOT a power of 4 (4's subgroup is the squares)
    # 2 is a non-residue-ish; check pohlig returns None
    result = pohlig_hellman(4, 2, 101, order=50)
    check("element outside subgroup -> None", result is None, f"{result}")

    # ---- 10. large exponent -------------------------------------------------------------
    p, g = 7919, 7
    order = multiplicative_order(g, p)
    x = order - 5
    h = pow(g, x, p)
    r = pohlig_hellman(g, h, p, order=order)
    check("large exponent recovered", r == x, f"{r} vs {x}")

    print(f"\n{PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL else 0)


if __name__ == "__main__":
    main()
