"""Tests for diffie_hellman.py -- Diffie-Hellman key exchange.

Self-running: prints PASS/FAIL per check, exits 1 if any fail. The exchange is checked against
the classic small example and the discrete-log solver.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import diffie_hellman as dh  # noqa: E402

failed = []


def check(name, cond):
    print(f"{'PASS' if cond else 'FAIL'} {name}")
    if not cond:
        failed.append(name)


# --- modular exponentiation & primality ------------------------------------
check("modexp matches direct power", dh.modexp(5, 6, 23) == 5 ** 6 % 23)
check("primes recognized", dh.is_probable_prime(48563) and dh.is_probable_prime(23))
check("composites rejected", not dh.is_probable_prime(48562))

# --- generators -------------------------------------------------------------
check("5 is a primitive root mod 23", dh.is_generator(5, 23))
check("4 is NOT a primitive root mod 23", not dh.is_generator(4, 23))
check("smallest generator of 23 is 5", dh.find_generator(23) == 5)
# a generator's powers hit every nonzero residue exactly once
g, p = 5, 23
powers = {dh.modexp(g, x, p) for x in range(p - 1)}
check("a generator's powers cover all nonzero residues", powers == set(range(1, p)))

# --- the classic exchange (p=23, g=5) --------------------------------------
A, B, sa, sb = dh.exchange(6, 15, 23, 5)
check("Alice's public value is g^a", A == dh.modexp(5, 6, 23))
check("Bob's public value is g^b", B == dh.modexp(5, 15, 23))
check("both parties derive the same secret", sa == sb)
check("the shared secret is g^(ab)", sa == dh.modexp(5, 6 * 15, 23))
# public_key / shared_secret helpers agree with exchange
check("public_key helper matches", dh.public_key(6, 23, 5) == A)
check("shared_secret helper matches", dh.shared_secret(B, 6, 23) == sa)

# --- safe-prime parameters --------------------------------------------------
pp, gg = dh.make_parameters(nbits=16, seed=3)
check("generated modulus is prime", dh.is_probable_prime(pp))
check("it is a SAFE prime (p-1)/2 also prime", dh.is_probable_prime((pp - 1) // 2))
check("the returned g is a generator", dh.is_generator(gg, pp))
check("parameter generation is deterministic per seed", dh.make_parameters(16, seed=3) == (pp, gg))
# a full exchange on the generated parameters agrees
A2, B2, sa2, sb2 = dh.exchange(12345, 54321, pp, gg)
check("exchange on generated params agrees", sa2 == sb2)
check("the secret is nonzero and < p", 0 < sa2 < pp)
# swapping secrets is symmetric: order doesn't matter
_, _, s1, s2 = dh.exchange(111, 222, pp, gg)
_, _, t1, t2 = dh.exchange(222, 111, pp, gg)
check("the exchange is symmetric in the two secrets", s1 == t1)

# --- the eavesdropper's problem: discrete log ------------------------------
# baby-step/giant-step recovers the exponent (feasible only for small p)
for x in (1, 7, 6, 21):
    h = dh.modexp(5, x, 23)
    rec = dh.discrete_log_bsgs(5, h, 23)
    check(f"BSGS recovers exponent {x} (mod order)", dh.modexp(5, rec, 23) == h)
# it can crack the generated small exchange -- showing the exchange is correct, and that
# security comes only from p being large
rec = dh.discrete_log_bsgs(gg, A2, pp)
check("BSGS cracks the small exchange (g^x = A)", dh.modexp(gg, rec, pp) == A2)
check("cracked exponent yields the same shared secret",
      dh.modexp(B2, rec, pp) == sa2)
# no solution when h is not in the subgroup generated by g
check("BSGS returns None when there is no solution", dh.discrete_log_bsgs(4, 3, 7) is None)


if failed:
    print(f"\n{len(failed)} FAILED: {failed}")
    sys.exit(1)
print("\nall diffie_hellman tests passed")
