"""Berlekamp-Massey: recovering the hidden linear recurrence behind a sequence.

Many sequences are generated by a LINEAR RECURRENCE: each term is a fixed linear combination of the
previous few, s[n] = c1*s[n-1] + c2*s[n-2] + ... + cL*s[n-L]. The Fibonacci numbers obey s[n] =
s[n-1] + s[n-2]; a linear-feedback shift register (LFSR) -- the workhorse of stream ciphers, CRCs, and
pseudorandom generators -- is exactly such a recurrence over GF(2). The Berlekamp-Massey algorithm
answers the inverse question: given only the first terms of a sequence, find the SHORTEST linear
recurrence that produces them. Its length L (the "linear complexity") measures how predictable the
sequence is -- a short recurrence means the whole infinite sequence is pinned down by a handful of
coefficients, which is why cryptographers demand high linear complexity from keystreams (a sequence an
LFSR of length L generates is fully recovered from just 2L output bits).

The algorithm scans the sequence left to right maintaining a current recurrence (an "LFSR") that
predicts every term seen so far. At each step it computes the DISCREPANCY between the predicted and
actual next term; if zero, the current recurrence still works. If not, it corrects the recurrence by
adding a scaled, shifted copy of the best PREVIOUS recurrence that had failed -- a construction that
provably keeps the length minimal. Over a field this runs in O(n^2) and yields the unique minimal
recurrence. This implementation works over the rationals (via Python's exact Fraction, so integer
sequences like Fibonacci are handled with no rounding) and, in a separate routine, over GF(2) for the
binary LFSR case that dominates coding and cryptography.

This module finds the minimal linear recurrence of a sequence over the rationals and over GF(2),
reports the linear complexity, and extrapolates further terms from the recovered recurrence. It is
verified by round-trip -- the recurrence it finds regenerates the input exactly and matches the known
recurrence for Fibonacci, Tribonacci, geometric, and polynomial sequences -- against a brute-force
search that confirms no shorter recurrence exists, and on GF(2) LFSR streams whose linear complexity
is recovered from a truncated prefix. Pure stdlib; a companion to the FFT, Reed-Solomon, and
number-theory notes."""

from __future__ import annotations

from fractions import Fraction


def berlekamp_massey(seq):
    """Shortest linear recurrence generating `seq` over the rationals.

    Returns a list of coefficients [c1, c2, ..., cL] (as Fractions) such that
    seq[n] = c1*seq[n-1] + c2*seq[n-2] + ... + cL*seq[n-L] for every n >= L. The length L is the
    linear complexity. Returns [] for the all-zero (or empty) sequence."""
    s = [Fraction(x) for x in seq]
    n = len(s)
    cur = []              # current recurrence coefficients (c1..cL)
    prev = []             # last recurrence before the most recent length change
    prev_disc = Fraction(1)
    prev_pos = -1         # index where `prev` was snapshotted
    for i in range(n):
        # discrepancy: actual term minus what the current recurrence predicts
        delta = s[i]
        for j, c in enumerate(cur):
            delta -= c * s[i - 1 - j]
        if delta == 0:
            continue
        if not cur:
            # first nonzero term with no recurrence yet: start a length-(i+1) recurrence
            cur = [Fraction(0)] * (i + 1)
            prev = []
            prev_disc = delta
            prev_pos = i
            continue
        # correct current recurrence by adding a scaled shift of the previous one
        coeff = delta / prev_disc
        shift = i - prev_pos
        new = list(cur)
        # term "1" at position (shift-1) minus coeff*prev, extended as needed
        need = shift + len(prev)
        if len(new) < need:
            new += [Fraction(0)] * (need - len(new))
        new[shift - 1] += coeff
        for j, pc in enumerate(prev):
            new[shift + j] -= coeff * pc
        if len(cur) < len(new):          # length increased: snapshot the OLD recurrence
            prev = cur
            prev_disc = delta
            prev_pos = i
        cur = new
    return cur


def linear_complexity(seq):
    """The length of the shortest linear recurrence generating `seq` (its linear complexity)."""
    return len(berlekamp_massey(seq))


def extend(seq, count, coeffs=None):
    """Extend `seq` by `count` further terms using its minimal recurrence (or the supplied
    coefficients). Returns only the newly generated terms."""
    if coeffs is None:
        coeffs = berlekamp_massey(seq)
    L = len(coeffs)
    if L == 0:
        return [Fraction(0)] * count
    hist = [Fraction(x) for x in seq]
    out = []
    for _ in range(count):
        nxt = sum(coeffs[j] * hist[-1 - j] for j in range(L))
        out.append(nxt)
        hist.append(nxt)
    return out


def regenerate(seq, coeffs=None):
    """Regenerate the whole sequence from its first L terms using the recurrence. Returns a list the
    same length as `seq`; if the recurrence is correct this equals `seq`."""
    if coeffs is None:
        coeffs = berlekamp_massey(seq)
    L = len(coeffs)
    s = [Fraction(x) for x in seq]
    if L == 0:
        return s
    out = s[:L]
    for i in range(L, len(s)):
        out.append(sum(coeffs[j] * out[i - 1 - j] for j in range(L)))
    return out


# --- GF(2) variant: the LFSR case (coding & cryptography) ------------------
def berlekamp_massey_gf2(bits):
    """Shortest LFSR (linear recurrence over GF(2)) generating the bit sequence `bits` (0/1).

    Returns (L, coeffs): L is the linear complexity and coeffs is the list [c1..cL] in {0,1} with
    bit[n] = XOR over j of coeffs[j]*bit[n-1-j]."""
    s = [int(b) & 1 for b in bits]
    n = len(s)
    # standard GF(2) BM using connection polynomials C(x), B(x)
    C = [1] + [0] * n
    B = [1] + [0] * n
    L = 0
    m = 1
    b = 1
    for i in range(n):
        # discrepancy
        d = s[i]
        for j in range(1, L + 1):
            d ^= C[j] & s[i - j]
        if d == 0:
            m += 1
        elif 2 * L <= i:
            T = list(C)
            for j in range(n + 1 - m):
                C[j + m] ^= B[j]
            L = i + 1 - L
            B = T
            b = 1
            m = 1
        else:
            for j in range(n + 1 - m):
                C[j + m] ^= B[j]
            m += 1
    coeffs = [C[j] for j in range(1, L + 1)]     # bit[n] = XOR coeffs[j-1]*bit[n-j]
    return L, coeffs


def lfsr_generate(coeffs, seed, count):
    """Generate `count` bits from an LFSR with the given GF(2) `coeffs` (c1..cL) and initial `seed`
    (the first L bits). bit[n] = XOR over j of coeffs[j]*bit[n-1-j]."""
    L = len(coeffs)
    out = [int(b) & 1 for b in seed[:L]]
    while len(out) < count:
        nxt = 0
        for j in range(L):
            nxt ^= coeffs[j] & out[-1 - j]
        out.append(nxt)
    return out[:count]


# --- brute-force reference --------------------------------------------------
def brute_min_recurrence(seq, max_len=None):
    """Find the shortest linear recurrence over the rationals by trying every length L and solving
    the resulting linear system on the first equations, then verifying on the rest. Returns the
    coefficient list, or None if none up to max_len fits. O(n^3) per length; small sequences only."""
    s = [Fraction(x) for x in seq]
    n = len(s)
    if all(x == 0 for x in s):
        return []
    if max_len is None:
        max_len = n // 2
    for L in range(1, max_len + 1):
        if n < 2 * L:
            break
        # solve for c1..cL from s[L..2L-1] = sum cj s[i-1-j]; use first L equations
        # build matrix M (L x L) and vector y
        M = [[s[L + r - 1 - j] for j in range(L)] for r in range(L)]
        y = [s[L + r] for r in range(L)]
        coeffs = _solve_linear(M, y)
        if coeffs is None:
            continue
        # verify on the entire sequence
        ok = True
        for i in range(L, n):
            pred = sum(coeffs[j] * s[i - 1 - j] for j in range(L))
            if pred != s[i]:
                ok = False
                break
        if ok:
            return coeffs
    return None


def _solve_linear(M, y):
    """Exact Gaussian elimination over Fractions. Returns the solution vector, or None if singular."""
    n = len(M)
    A = [[Fraction(M[r][c]) for c in range(n)] + [Fraction(y[r])] for r in range(n)]
    for col in range(n):
        piv = None
        for r in range(col, n):
            if A[r][col] != 0:
                piv = r
                break
        if piv is None:
            return None
        A[col], A[piv] = A[piv], A[col]
        inv = A[col][col]
        A[col] = [v / inv for v in A[col]]
        for r in range(n):
            if r != col and A[r][col] != 0:
                f = A[r][col]
                A[r] = [A[r][c] - f * A[col][c] for c in range(n + 1)]
    return [A[r][n] for r in range(n)]
