"""CYK parsing: deciding membership in a context-free language by dynamic programming.

Regular languages are recognised by finite automata, but nested structure -- balanced parentheses,
arithmetic expressions, the grammar of a programming language -- needs CONTEXT-FREE grammars, which
can be ambiguous and are not, in general, parseable left to right. The Cocke-Younger-Kasami algorithm
(CYK) decides whether a string is generated by a context-free grammar in O(n^3 * |grammar|) by
dynamic programming over substrings, and it works for ANY context-free grammar -- ambiguous ones
included -- which recursive-descent and LL/LR parsers cannot claim.

CYK needs the grammar in CHOMSKY NORMAL FORM: every rule is either A -> B C (two nonterminals) or
A -> a (one terminal). Then it fills a triangular table where cell (i, length) holds the set of
nonterminals that can derive the substring starting at i of that length:

    length-1 cells come straight from the terminal rules,
    a length-L span is filled by trying every split point: if B derives the left part and C the
        right, and A -> B C is a rule, then A derives the whole span.

The string is in the language iff the start symbol appears in the cell covering the whole string.
Because it considers all splits, CYK also COUNTS the number of distinct parse trees (the degree of
ambiguity) with the same recurrence, and the backpointers reconstruct one parse tree.

This module represents a CNF grammar, recognises strings, counts parse trees, and extracts a parse
tree; it also converts a restricted general CFG (with unit and terminal-mixed rules) to CNF. Validated
against brute force: membership matches an exhaustive recursive derivation search on small grammars
and strings; the parse-tree count matches the number of distinct derivations found by that search;
classic grammars (balanced parentheses, a^n b^n, palindromes, simple arithmetic) accept exactly the
right strings; and an ambiguous grammar reports more than one tree. Pure stdlib; the context-free
companion to the Thompson NFA (regular) and shunting-yard (operator-precedence) tools."""

from __future__ import annotations

from collections import defaultdict


class CNFGrammar:
    """A context-free grammar in Chomsky Normal Form.

    binary_rules: iterable of (A, B, C) meaning A -> B C.
    terminal_rules: iterable of (A, a) meaning A -> a.
    start: the start symbol. Nonterminals and terminals are any hashable tokens."""

    def __init__(self, binary_rules, terminal_rules, start):
        self.start = start
        self.binary = list(binary_rules)
        self.terminal = list(terminal_rules)
        # index: for fast lookup, map (B, C) -> set of A, and terminal a -> set of A
        self.by_pair = defaultdict(set)
        for A, B, C in self.binary:
            self.by_pair[(B, C)].add(A)
        self.by_terminal = defaultdict(set)
        for A, a in self.terminal:
            self.by_terminal[a].add(A)
        self.nonterminals = ({A for A, _, _ in self.binary}
                             | {A for A, _ in self.terminal} | {start})


def _table(grammar, tokens):
    """Fill the CYK table. table[(i, L)] = set of nonterminals deriving tokens[i:i+L]."""
    n = len(tokens)
    table = defaultdict(set)
    for i, tok in enumerate(tokens):
        table[(i, 1)] = set(grammar.by_terminal.get(tok, set()))
    for L in range(2, n + 1):
        for i in range(0, n - L + 1):
            cell = table[(i, L)]
            for split in range(1, L):
                left = table[(i, split)]
                right = table[(i + split, L - split)]
                if not left or not right:
                    continue
                for B in left:
                    for C in right:
                        cell |= grammar.by_pair.get((B, C), set())
    return table, n


def recognize(grammar, tokens):
    """True if the grammar generates the token sequence."""
    tokens = list(tokens)
    if not tokens:
        return False  # CNF (without epsilon rules) cannot derive the empty string
    table, n = _table(grammar, tokens)
    return grammar.start in table[(0, n)]


def count_parses(grammar, tokens):
    """Number of distinct parse trees (degree of ambiguity) for the token sequence."""
    tokens = list(tokens)
    n = len(tokens)
    if n == 0:
        return 0
    # counts[(i, L)][A] = number of ways A derives tokens[i:i+L]
    counts = defaultdict(lambda: defaultdict(int))
    for i, tok in enumerate(tokens):
        for A in grammar.by_terminal.get(tok, set()):
            counts[(i, 1)][A] += 1
    for L in range(2, n + 1):
        for i in range(0, n - L + 1):
            cell = counts[(i, L)]
            for split in range(1, L):
                left = counts[(i, split)]
                right = counts[(i + split, L - split)]
                if not left or not right:
                    continue
                for B, nb in left.items():
                    for C, nc in right.items():
                        for A in grammar.by_pair.get((B, C), set()):
                            cell[A] += nb * nc
    return counts[(0, n)].get(grammar.start, 0)


def parse_tree(grammar, tokens):
    """Return one parse tree as nested tuples (A, left_tree, right_tree) or (A, terminal),
    or None if the string is not in the language."""
    tokens = list(tokens)
    n = len(tokens)
    if n == 0:
        return None
    table, _ = _table(grammar, tokens)
    if grammar.start not in table[(0, n)]:
        return None

    def build(i, L, symbol):
        if L == 1:
            return (symbol, tokens[i])
        for split in range(1, L):
            for B in table[(i, split)]:
                for C in table[(i + split, L - split)]:
                    if symbol in grammar.by_pair.get((B, C), set()):
                        return (symbol, build(i, split, B), build(i + split, L - split, C))
        return None

    return build(0, n, grammar.start)


def tree_yield(tree):
    """The terminal string (leaf sequence) of a parse tree."""
    if len(tree) == 2:
        return [tree[1]]
    return tree_yield(tree[1]) + tree_yield(tree[2])


# --- brute-force reference ---------------------------------------------------
def brute_derivations(grammar, tokens, symbol=None):
    """Count derivations of `tokens` from `symbol` (default start) by exhaustive recursion.
    Exponential -- for small strings only. Serves as the independent reference for CYK."""
    tokens = list(tokens)
    if symbol is None:
        symbol = grammar.start

    from functools import lru_cache

    binary_by_head = defaultdict(list)
    for A, B, C in grammar.binary:
        binary_by_head[A].append((B, C))
    terminal_by_head = defaultdict(set)
    for A, a in grammar.terminal:
        terminal_by_head[A].add(a)

    memo = {}

    def derive(sym, seq):
        seq = tuple(seq)
        key = (sym, seq)
        if key in memo:
            return memo[key]
        total = 0
        if len(seq) == 1 and seq[0] in terminal_by_head[sym]:
            total += 1
        if len(seq) >= 2:
            for (B, C) in binary_by_head[sym]:
                for split in range(1, len(seq)):
                    total += derive(B, seq[:split]) * derive(C, seq[split:])
        memo[key] = total
        return total

    return derive(symbol, tokens)
