"""Hidden Markov models: decoding and learning from sequences with hidden state.

A hidden Markov model describes a sequence you CAN see (the emissions) generated by a chain of
states you CANNOT (the hidden path). At each step the state jumps according to a transition matrix,
then emits an observable symbol according to an emission matrix. The classic picture: a fair/loaded
die switched behind a curtain, or the weather (hidden) driving whether you carry an umbrella
(observed). Three questions have three exact algorithms, all dynamic programming over the trellis:

  EVALUATE -- how likely is this observation sequence? The FORWARD algorithm sums the probability
      of every path consistent with the data in O(T k^2), where a naive sum is O(k^T).
  DECODE -- what hidden path best explains it? VITERBI is the same recursion with max replacing
      sum, plus backpointers, giving the single most-likely state sequence.
  LEARN -- what transition/emission matrices fit unlabeled sequences? BAUM-WELCH is EM: the
      FORWARD-BACKWARD pass gives the posterior probability of each state (and each transition) at
      each step, and those soft counts re-estimate the matrices. Each round cannot decrease the
      data likelihood -- the standard correctness check.

All of it runs in LOG SPACE with log-sum-exp so long sequences don't underflow to zero. This module
implements forward (log-likelihood), Viterbi (best path), forward-backward (posterior marginals),
and Baum-Welch training with multi-restart -- verified that Viterbi recovers a planted state path,
that forward and backward agree on the likelihood, that Baum-Welch climbs it monotonically, and
that training recovers a known loaded-die model. Pure stdlib; the sequential companion to the
Gaussian-mixture / EM note."""

from __future__ import annotations

import math

NEG_INF = float("-inf")


def _logsumexp(vals):
    m = max(vals)
    if m == NEG_INF:
        return NEG_INF
    return m + math.log(sum(math.exp(v - m) for v in vals))


def _log(x):
    return math.log(x) if x > 0 else NEG_INF


class HMM:
    """A discrete-emission hidden Markov model.

    start[i]      P(first state = i)
    trans[i][j]   P(state j at t+1 | state i at t)
    emit[i][s]    P(symbol s | state i)
    """

    def __init__(self, start, trans, emit):
        self.start = list(start)
        self.trans = [list(row) for row in trans]
        self.emit = [list(row) for row in emit]
        self.n = len(start)                 # number of hidden states
        self.m = len(emit[0])               # size of the observation alphabet

    # --- log-space parameter views ----------------------------------------
    def _log_start(self):
        return [_log(p) for p in self.start]

    def _log_trans(self):
        return [[_log(p) for p in row] for row in self.trans]

    def _log_emit(self):
        return [[_log(p) for p in row] for row in self.emit]

    # --- EVALUATE: forward algorithm --------------------------------------
    def forward(self, obs):
        """Log-alpha trellis. alpha[t][i] = log P(obs[:t+1], state_t = i)."""
        ls, lt, le = self._log_start(), self._log_trans(), self._log_emit()
        T = len(obs)
        alpha = [[NEG_INF] * self.n for _ in range(T)]
        for i in range(self.n):
            alpha[0][i] = ls[i] + le[i][obs[0]]
        for t in range(1, T):
            for j in range(self.n):
                alpha[t][j] = _logsumexp([alpha[t - 1][i] + lt[i][j] for i in range(self.n)]) \
                    + le[j][obs[t]]
        return alpha

    def log_likelihood(self, obs):
        """log P(obs) under the model (marginalizing over all hidden paths)."""
        alpha = self.forward(obs)
        return _logsumexp(alpha[-1])

    def backward(self, obs):
        """Log-beta trellis. beta[t][i] = log P(obs[t+1:] | state_t = i)."""
        lt, le = self._log_trans(), self._log_emit()
        T = len(obs)
        beta = [[NEG_INF] * self.n for _ in range(T)]
        for i in range(self.n):
            beta[T - 1][i] = 0.0
        for t in range(T - 2, -1, -1):
            for i in range(self.n):
                beta[t][i] = _logsumexp([lt[i][j] + le[j][obs[t + 1]] + beta[t + 1][j]
                                         for j in range(self.n)])
        return beta

    # --- DECODE: Viterbi ---------------------------------------------------
    def viterbi(self, obs):
        """Most-likely hidden state path and its log-probability."""
        ls, lt, le = self._log_start(), self._log_trans(), self._log_emit()
        T = len(obs)
        delta = [[NEG_INF] * self.n for _ in range(T)]
        back = [[0] * self.n for _ in range(T)]
        for i in range(self.n):
            delta[0][i] = ls[i] + le[i][obs[0]]
        for t in range(1, T):
            for j in range(self.n):
                best_i, best_v = 0, NEG_INF
                for i in range(self.n):
                    v = delta[t - 1][i] + lt[i][j]
                    if v > best_v:
                        best_v, best_i = v, i
                delta[t][j] = best_v + le[j][obs[t]]
                back[t][j] = best_i
        # backtrack from the best final state
        last = max(range(self.n), key=lambda i: delta[T - 1][i])
        path = [last]
        for t in range(T - 1, 0, -1):
            last = back[t][last]
            path.append(last)
        path.reverse()
        return path, delta[T - 1][max(range(self.n), key=lambda i: delta[T - 1][i])]

    # --- posterior marginals ----------------------------------------------
    def posterior(self, obs):
        """gamma[t][i] = P(state_t = i | obs) via forward-backward."""
        alpha = self.forward(obs)
        beta = self.backward(obs)
        T = len(obs)
        ll = _logsumexp(alpha[-1])
        gamma = []
        for t in range(T):
            row = [alpha[t][i] + beta[t][i] - ll for i in range(self.n)]
            gamma.append([math.exp(v) for v in row])
        return gamma

    def predict(self, obs):
        """Viterbi best-path state labels (convenience wrapper)."""
        return self.viterbi(obs)[0]


def _normalize(v):
    s = sum(v)
    return [x / s for x in v] if s > 0 else [1.0 / len(v)] * len(v)


def baum_welch(sequences, n_states, n_symbols, max_iter=100, tol=1e-5, seed=0):
    """Train an HMM from unlabeled sequences by EM (Baum-Welch).

    Returns (model, history) where history is the total log-likelihood per iteration -- which is
    guaranteed non-decreasing. Parameters are initialized randomly (LCG, high bits)."""
    state = seed & 0xFFFFFFFF

    def rand():
        nonlocal state
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        return 0.5 + (state >> 16) / 65536.0     # in [0.5, 1.5): keeps init away from exact ties

    start = _normalize([rand() for _ in range(n_states)])
    trans = [_normalize([rand() for _ in range(n_states)]) for _ in range(n_states)]
    emit = [_normalize([rand() for _ in range(n_symbols)]) for _ in range(n_states)]
    model = HMM(start, trans, emit)

    history = []
    prev = NEG_INF
    for _ in range(max_iter):
        # accumulators for the M-step
        start_acc = [0.0] * n_states
        trans_num = [[0.0] * n_states for _ in range(n_states)]
        trans_den = [0.0] * n_states
        emit_num = [[0.0] * n_symbols for _ in range(n_states)]
        emit_den = [0.0] * n_states
        total_ll = 0.0

        lt, le = model._log_trans(), model._log_emit()
        for obs in sequences:
            T = len(obs)
            alpha = model.forward(obs)
            beta = model.backward(obs)
            ll = _logsumexp(alpha[-1])
            total_ll += ll

            # gamma[t][i] and expected transitions xi[t][i][j] (in prob space)
            for t in range(T):
                g = [math.exp(alpha[t][i] + beta[t][i] - ll) for i in range(n_states)]
                if t == 0:
                    for i in range(n_states):
                        start_acc[i] += g[i]
                for i in range(n_states):
                    emit_num[i][obs[t]] += g[i]
                    emit_den[i] += g[i]
                    if t < T - 1:
                        trans_den[i] += g[i]
            for t in range(T - 1):
                for i in range(n_states):
                    for j in range(n_states):
                        xi = math.exp(alpha[t][i] + lt[i][j] + le[j][obs[t + 1]]
                                      + beta[t + 1][j] - ll)
                        trans_num[i][j] += xi

        history.append(total_ll)

        # M-step: renormalize the soft counts into probabilities
        n_seq = len(sequences)
        start = _normalize([start_acc[i] + 1e-12 for i in range(n_states)])
        trans = [_normalize([trans_num[i][j] + 1e-12 for j in range(n_states)])
                 for i in range(n_states)]
        emit = [_normalize([emit_num[i][s] + 1e-12 for s in range(n_symbols)])
                for i in range(n_states)]
        model = HMM(start, trans, emit)

        if total_ll - prev < tol and prev != NEG_INF:
            break
        prev = total_ll

    return model, history


def baum_welch_best(sequences, n_states, n_symbols, restarts=6, max_iter=100, tol=1e-5, seed=0):
    """Train from several random inits, keep the highest-likelihood model."""
    best_model, best_ll = None, NEG_INF
    for r in range(restarts):
        model, hist = baum_welch(sequences, n_states, n_symbols, max_iter=max_iter, tol=tol,
                                 seed=(seed + r * 6151) & 0xFFFFFFFF)
        if hist[-1] > best_ll:
            best_ll, best_model = hist[-1], model
    return best_model, best_ll
