"""The Mandelbrot set: infinite complexity from z -> z^2 + c.

Pick a complex number c and iterate z_{n+1} = z_n^2 + c starting from z = 0. For some c the
orbit stays bounded forever; for others it flies off to infinity. The Mandelbrot set is
exactly the set of c for which the orbit stays bounded -- and its boundary is one of the most
intricate objects in mathematics, an infinitely detailed fractal that contains tiny copies of
itself at every scale, all generated by that one-line rule.

The key fact that makes it computable: once |z| exceeds 2 the orbit is guaranteed to escape
to infinity. So you iterate until |z| > 2 (escape) or hit an iteration cap (assume bounded).
The number of steps to escape -- the "escape time" -- is what colours the famous images: points
just outside the set take longer and longer to escape as you approach the boundary, painting
the filaments and spirals.

The set lives in |c| <= 2 and is connected. Its main cardioid (the big bulb) is the set of c
for which z -> z^2 + c has a stable fixed point, |c - 1/4| region; the disc to its left,
centred at c = -1 with radius 1/4, is the period-2 bulb. The real slice from -2 to 1/4 maps
directly onto the logistic map's period-doubling route to chaos -- same dynamics, complex
dress.

This module gives one iteration, the escape time of a point, membership in the set, the
main-cardioid and period-2-bulb quick tests (which skip iteration for the biggest regions),
and the escaped-fraction of a region, and reproduces the |z|>2 escape criterion and the known
in/out points. Pure stdlib (manual complex arithmetic via tuples, though Python complex works
too); the complex-dynamics companion to the Henon and logistic-map notes.
"""

from __future__ import annotations

import math

ESCAPE_RADIUS = 2.0


def iterate(z: complex, c: complex) -> complex:
    """One step of the map z -> z^2 + c."""
    return z * z + c


def escape_time(c: complex, max_iter: int = 100) -> int:
    """Number of iterations for the orbit of z0=0 under z->z^2+c to exceed |z|=2. Returns
    max_iter if it never escapes within the cap (treated as 'in the set'). Small for points
    far outside, large near the boundary."""
    z = 0j
    for n in range(max_iter):
        z = z * z + c
        if abs(z) > ESCAPE_RADIUS:
            return n + 1
    return max_iter


def in_set(c: complex, max_iter: int = 100) -> bool:
    """True if c is (numerically) in the Mandelbrot set: its orbit stays bounded for max_iter
    iterations."""
    return escape_time(c, max_iter) >= max_iter


def in_main_cardioid(c: complex) -> bool:
    """Exact test for the main cardioid (the big body): with q = (c - 1/4), the point is inside
    if q(q + (c-1/4))... -- use the standard form
    p = |c - 1/4|; inside iff |c - 1/4| <= 1/2 - Re? Use the cardioid inequality:
    q = (Re(c) - 1/4)^2 + Im(c)^2; inside iff q (q + (Re(c) - 1/4)) <= Im(c)^2 / 4."""
    x, y = c.real, c.imag
    q = (x - 0.25) ** 2 + y * y
    return q * (q + (x - 0.25)) <= 0.25 * y * y


def in_period2_bulb(c: complex) -> bool:
    """Exact test for the period-2 bulb: the disc of radius 1/4 centred at c = -1."""
    x, y = c.real, c.imag
    return (x + 1.0) ** 2 + y * y <= 1.0 / 16.0


def definitely_in_set(c: complex) -> bool:
    """Fast, exact membership for the two largest regions (main cardioid + period-2 bulb),
    skipping iteration. True guarantees membership; False just means 'use escape_time'."""
    return in_main_cardioid(c) or in_period2_bulb(c)


def escaped_fraction(re_min: float, re_max: float, im_min: float, im_max: float,
                     nx: int = 60, ny: int = 60, max_iter: int = 100) -> float:
    """Fraction of a grid over the given complex rectangle whose points escape (are NOT in the
    set). ~1 for a region far outside, <1 straddling the set."""
    escaped = 0
    total = nx * ny
    for i in range(nx):
        re = re_min + (re_max - re_min) * (i + 0.5) / nx
        for j in range(ny):
            im = im_min + (im_max - im_min) * (j + 0.5) / ny
            if not in_set(complex(re, im), max_iter):
                escaped += 1
    return escaped / total
